name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]  # 同时支持 main 和 master 分支
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          cache: true
      
      - name: Enable web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get
          
      - name: Verify dependencies
        run: flutter pub outdated
        
      - name: Build web
        run: |
          flutter build web \
            --release \
            --base-href "/${{ github.event.repository.name }}/" \
            --web-renderer html \
            --pwa-strategy offline-first
            
      - name: Configure Pages
        run: |
          touch build/web/.nojekyll
          cp build/web/index.html build/web/404.html
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages' 